apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{.Release.Name}}-{{.Values.persistantVolume.name}}-pv
spec:
  storageClassName: {{.Values.persistantVolume.storageClassName}}
  capacity:
    storage: {{ .Values.persistantVolume.capacity.storage}}
  accessModes:
    {{- toYaml .Values.persistantVolume.accessModes | nindent 4 }}
  hostPath:
    path: {{.Values.persistantVolume.hostPath.path}}
