apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Release.Name}}-{{.Values.persistantVolumeClaim.name}}-pvc
spec:
  storageClassName: {{.Values.persistantVolumeClaim.storageClassName}}
  accessModes:
    {{- toYaml .Values.persistantVolumeClaim.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{.Values.persistantVolumeClaim.resources.requests.storage}}
