apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name }}-{{ .Values.services.webapp.name}}
spec:
  ports:
  - port: {{.Values.services.webapp.port}}
    protocol: TCP
    targetPort: {{.Values.services.webapp.targetPort}}
  selector:
    app: {{ .Values.webapp.name}}
  type: LoadBalancer
