---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-{{.Values.webapp.name}}
spec:
  selector:
    matchLabels:
      app: {{.Values.webapp.name}}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.webapp.name}}
      name: {{.Release.Name }}-{{ .Values.webapp.name}}
    spec:
      imagePullSecrets:
      - name: gcp-artifact-registry
      initContainers:
      - name: wait-for-postgres
        image: busybox
        command: ['/bin/sh', '-c', 'until nc -z {{.Values.services.postgres.name}} 5432; do echo "Waiting for PostgreSQL to be ready"; sleep 2; done;']
      containers:
      - image: {{ .Values.webapp.image.repository }}:{{ .Values.webapp.image.tag}}
        name: {{ .Values.webapp.name}}
        env:
        - name: PG_USER
          valueFrom:
            secretKeyRef:
              name: {{.Release.Name}}-{{.Values.secret.name}}
              key: PG_USER
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{.Release.Name}}-{{.Values.secret.name}}
              key: PG_PASSWORD
        - name: PG_DB
          valueFrom:
            secretKeyRef:
              name: {{.Release.Name}}-{{.Values.secret.name}}
              key: PG_DB
        - name: PG_HOST
          valueFrom:
            secretKeyRef:
              name: {{.Release.Name}}-{{.Values.secret.name}}
              key: PG_HOST
        
