name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Adjust to match the branches you want to trigger this action

jobs:
  setup-build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Authenticate to Google Cloud
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker us-east1-docker.pkg.dev --quiet

      - name: Build and push Docker image with version tag
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: |
            us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/kubernetes-webapp/webapp:latest
          file: ./webapp/Dockerfile

      - name: Verify image in GCP Container Registry
        run: gcloud container images list-tags us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/kubernetes-webapp
