name: Package and Push Helm Chart

on:
  push:
    branches:
      - main  

jobs:
  setup-build-publish-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Gcloud CLI
        run: gcloud auth configure-docker us-east1-docker.pkg.dev --quiet
      
      - name: Package Helm chart
        run: helm package ./pern-chart
                                                        
      - name: Push Helm chart
        run: |
          helm push pern-chart-0.1.0.tgz oci://us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/kubenetes-helm-chart

      - name: Verify chart in GCP Artifact Registry
        run: gcloud artifacts packages list --repository=helm-repo --location=${{ secrets.REGION }}
